Create issue templates for different use cases
OpenMS/pyopenms-docs pull request #308
Opened 2022-10-22 13:24 UTC by Happy-reindeer007

Creates bug report and documentation issue templates

Closes #305

2022-10-22 15:19 UTC, jpfeuffer requested changes

2022-10-22 15:19 UTC, jpfeuffer commented on .github/ISSUE_TEMPLATE/bug-report.md
> +labels: ''
```suggestion
labels: 'bug'
```

2022-10-22 15:19 UTC, jpfeuffer commented on .github/ISSUE_TEMPLATE/documentation-issue.md
> +labels: ''
```suggestion
labels: 'documentation'
```

2022-10-22 15:19 UTC, jpfeuffer commented on .github/ISSUE_TEMPLATE/bug-report.md
> + - Version:
```suggestion
 - OS Version:
```

2022-10-22 15:19 UTC, jpfeuffer commented on .github/ISSUE_TEMPLATE/bug-report.md
> + - Python version:
```suggestion
 - Python version:
 - pyopenms version:
 - How did you install pyopenms? Please cross a box with an X.
     - [ ] conda::bioconda: Specify your conda/mamba command and/or your environment with `conda list`.
     - [ ] conda::openms: Specify your conda/mamba command and/or your environment with `conda list`.
     - [ ] pip
     - [ ] nightly wheel
     - [ ] built from source
```

2022-10-22 15:21 UTC, jpfeuffer requested changes

2022-10-22 15:21 UTC, jpfeuffer commented on .github/ISSUE_TEMPLATE/bug-report.md
> +about: Create a report when something isn't working
```suggestion
about: Create a report when something isn't working with your python code using pyopenms
```

2022-10-22 15:21 UTC, jpfeuffer commented on .github/ISSUE_TEMPLATE/documentation-issue.md
> +about: Create a report if there is a problem with the documentation
```suggestion
about: Create a report if there is a problem with the documentation. E.g., unclear, typography, not reproducible or incomplete
```

2022-10-22 15:22 UTC, jpfeuffer commented
Thanks!!

2022-10-22 19:09 UTC, Happy-reindeer007 commented
You’re welcome, I’ve just applied the changes that you suggested.

BTW, I’ve just noticed that this repo hasn’t got the hacktoberfest label, even though the issue had it, so it’s not counting towards the event. Would you mind adding it? Thanks!

2022-10-22 20:27 UTC, jpfeuffer commented
I added the label.
Btw did you know that you can add suggestions to a batch and commit them altogether?
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request

2022-10-22 21:50 UTC, Happy-reindeer007 commented
> Btw did you know that you can add suggestions to a batch and commit them altogether?
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request

Yeah, I tried to but for some reason it wasn’t letting me…

2022-10-27 19:20 UTC, Happy-reindeer007 commented
Hi there! Did you have time to take a look at the changes?

2022-10-28 09:59 UTC, merged